dturvene psmouse-alps-dst-0.1

diff --git a/README b/README
--- a/README
+++ b/README
@@ -1,27 +1,3 @@
-$Id: README 720 2012-10-02 00:14:28Z dturvene $
-
-History
--------
-0.1: hacked in rudimentary support for the Dell IR15 N5110.  Nothing else 
-     should work - probably causing a kernel panic.
-0.2: add logic to isolate N5110 changes from previously supported devices
-     expand diagnostics to capture touchpad protocol
-     add kernel parameter to enable/disable runtime packet debug
-     enabled edge scrolling for N5110
-     add more shell scripts to control/debug device
-0.3: clean up a potential null pointer exception
-     added signature for Dell I17R 7720 based on user confirmaton to V6 protocol
-     disable multi-touch for V6 protocol
-     include alps.sh helper scripts
-0.4: integrate multi-touch support from florin9doi
-     default alps_debug=0, can be enabled through sysfs
-     code cleanup
-0.5: elevate persistent syslog to psmouse_info for production/release capture
-      of alps signature and command response - both of which determine control 
-      protocol
-
-Background
-----------
 This README documents my work to reverse engineer the Alps touchpad on a
 Dell N5110 for Linux.  When I first purchased the laptop and installed
 Ubuntu 12.04, I noticed that the touchpad behaved erratically.  It would
@@ -66,6 +42,10 @@ The ALPS touchpad is working on my N5110.  I can control the touchpad
 somewhat via xinput and the System Settings->Touchpad widget.  I think
 it can still be tightened up but, at least, it's usable now.
 
+One word about the source.  I have added a MOD_DST define in alps.h for
+special handling.  This must be set for the N5110 touchpad.  If it is
+set, probably all other Alps touchpads will not work.
+
 Dave Turvene
 
 [1] http://swapspace.forshee.me/2011/11/touchpad-protocol-reverse-engineering.html
@@ -73,11 +53,32 @@ Dave Turvene
 [3] http://www.spinics.net/lists/linux-input/msg21993.html
 [4] file:///usr/src/linux-source-3.2.0/linux-3.2.0/Documentation/input/alps.txt
 
-bash shell scripts
-------------------
-See alps.sh for support scripts.
+function build_alps() {
 
+    echo "Build the psmouse DLKM"
 
+    echo "clean the current dlkm if it exists"
+    sudo dkms remove psmouse/alps-dst-0.1 --all
+    sudo dkms build psmouse/alps-dst-0.1
 
+    if [[ $? == 0 ]]; then
+        sudo dkms install psmouse/alps-dst-0.1
+        sudo rmmod psmouse && sudo modprobe -v psmouse
+    else
+        printf "Build failed\n"
+        cat /var/lib/dkms/psmouse/alps-dst-0.1/build/make.log
+    fi
+}
 
+function set_system() {
 
+   echo "Support functions tuning the Alps touchpad"
+
+   echo "Get the Alps touchpad input ID"
+   ID=$(xinput --list | grep "AlpsPS/2" | sed -e 's/.*id=\([1-9]\+\).*/\1/')
+
+   echo "Get the Velocity Scaling property and set it to a faster value"
+   CSPD=$(xinput list-props 14 | grep "Velocity Scaling" | sed -e 's/.*(\([0-9]\+\)).*/\1/')
+   xinput set-prop $ID $CSPD 40
+
+}
